### PR TITLE
Update readme.md and correct spelling

### PR DESCRIPTION
**Pull request by adam-weber**
Change `untie` to `unit`. I hate to be the guy correcting small changes..but this caught my eye. Looking forward to contributing more meaningful work in the future.

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Hi Adam, 
every bit helps, it is appreciated. However the hardest task might still be up ahead. The system could not make sure you signed the Eclipse Contributor Approval, which is a prerequisite for accepting contributions here.

There are several moving parts to get this done

- [x] You need to "sign-off" your commits (git commit -s) (I think you did)
- [ ] You need a account on https://www.eclipse.org (free), preferably with the same email address used in "signed-off" (not sure that is a hard requirement)
- [ ] In your Eclipse.org account you have the chance to "sign" (type your name, click a checkbox) the ECA. Read it for yourself, but basically it says by "signing off" commits you agree that your code is released under projct license (Apache-2.0) in this case, and that it is your work
- [ ] Tell Eclipse the name of your Github account, to do that, you need to go to your account settigns in eclipse and under `Social Media Links`->`Github Username` put yout github username `adam-weber` in your case


After that is done you should get a nice green checkmark at the ECA check

**Comment by erikbosch** [comment]
> Hi Adam, every bit helps, it is appreciated. However the hardest task might still be up ahead. The system could not make sure you signed the Eclipse Contributor Approval, which is a prerequisite for accepting contributions here.
> 
> There are several moving parts to get this done
> 
>     * [x]  You need to "sign-off" your commits (git commit -s) (I think you did)
> 

According to the blog post below a signoff (`-s`) is no longer required. Eclipse use the author-field instead, and currently it complains as `agweber@****.edu` does not have a valid ECA:

_Could not validate the users ECA sign-off status. Please ensure that the e-mail address of all contributing accounts match a valid Eclipse Foundation account with a valid ECA._


https://www.eclipse.org/lists/eclipse.org-committers/msg01291.html

**Comment by adam-weber** [comment]
@SebastianSchildt @erikbosch thanks for the help! should be all set now

**Review by erikbosch — APPROVED** [review]

**Review by SebastianSchildt — APPROVED** [review]
Looking good now. Another (small) step forward. Thank you

**Pull request merged**
