### PR TITLE
Fraunhofer IEM - PS5 Formular 1 feeder 

### PR DESCRIPTION
**Pull request by DrySlime**
Hello, 

My Name is Christopher Seibel and I am a student working at Fraunhofer IEM. 
In my internship i had a the chance to write a simple provider, as a non-commercial research project, which takes the telemetrydata from the PS5 game "Formular 1" and feeds it to the KUKSA.val Databroker. 

In the ReadMe you can also find a link to a Video of the final result. There we can see a visual representation of the data after it was sent to the Databroker.

This is my first time doing a pull request and I apologize for rookie mistakes, i am open for any feedback.

with kind regards,
Christopher Seibel

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Hi Christopher, thank you for the PR. First step to get this in a good shape: The tests currently show, you have not "signed" the Eclipse Contributor approval. You did your commits with your Fraunhofer address, so basically what needs to be done is 

 - Create an eclipse account https://accounts.eclipse.org/user/register 
 - and sign the eclipse eca https://www.eclipse.org/legal/ECA.php 
 
FAQ: https://www.eclipse.org/legal/ecafaq.php

No costs :) and also not much legalese involved. basically the ECA roughly "by signing miy commits with my mail adress, I assure I created the code myself and/or have the right to provide it to Eclipse under the project license" (Apache-2.0 in our case)

wrt to testing, anyone in the team has a PS 5 :) ? @lukasmittag  or @Chrylo  maybe?

**Comment by DrySlime** [comment]
Hello again,
I now had the time to try and fix the following problems:
Spdx comments are now in the Python file.
I created an Eclipse Account and signed the ECA
My Code now follows the Flake8 rules.

Please feel free to point out further errors from my part.

**Comment by DrySlime** [comment]
Hey, 
I just double checked and i have used the same email and username

**Comment by DrySlime** [comment]
image

**Comment by SebastianSchildt** [comment]
- SPDX passes, yay!
 - ECA is weird, I checked: 
image
Not sure, can ECA not signed retroactively? Let's ignore for now, maybe a squash might fix it

 - pre-commit still issues in
Fixing README.md
Fixing fone2val/config/carTelemetry_feeder.ini

I think README may only miss a newline at the end of the file. Not sure what is in the ini. To "force" pre-commit to check it, install it in the checked out folder as described here https://github.com/eclipse/kuksa.val.feeders, then "modify" both files (i.e. adding a sapce somehwere) do a git add, and then git commit. That will trigger the pre-commit hook to run locally and modifying the files. Then I think they can just be "git add" again, and then "git commit" . In doubt @erikbosch knows best

**Comment by erikbosch** [comment]
As suggested by Sebastian, do a local squash and if then rebase on latest master, and then a git force push, that should hopefully fix the ECA tickets.

**Pull request closed without merging**
